### ISSUE TITLE
Add doc.go

### ISSUE THREAD

**Issue by voidabhi** [mitchellh/pointerstructure#3]

**Comment by mitchellh** [comment]
Hi! Can you please provide more detail? Thanks!

**Comment by voidabhi** [comment]
@mitchellh `doc.go`  file defining package name and description

**Comment by mitchellh** [comment]
We do that in `pointer.go`. If you run `go doc` against this package you'll get that output.

**Comment by voidabhi** [comment]
@mitchellh cool my bad!
